### ISSUE TITLE
Onde posso pegar os dados diariamente?

### ISSUE THREAD

**Issue by JoaoCarabetta** [flaviovdf/covid19#1]
Opa Flávio,

Estou fazendo um projeto para avaliar os limites da estrutura de saúde dos municípios brasileiros em resposta a pandemia.

Seus dados seriam muito úteis para alimentar o R0 da ferramenta. Como que faço pra baixar esses dados diariamente?

Até mesmo, podemos pensar em fazê-los para as capitais também.

**Comment by flaviovdf** [comment]
Eu usei os dados do Brasil.io https://drive.google.com/drive/folders/1l3tiwrGEcJEV3gxX0yP-VMRNaE1MLfS2

**Comment by flaviovdf** [comment]
E sim, da para fazer para as capitais, decidi por estado pois tem a informação de casos não locais. Para estimar a capacidade do SUS eu já brinquei com um modelo SEIR. Os resultados não são bons :(

**Comment by JoaoCarabetta** [comment]
Por que os resultados não são bons? Não fitou?

**Comment by JoaoCarabetta** [comment]
Eu queria a estimação do R0 que vc calculou mesmo

**Comment by JoaoCarabetta** [comment]
Tu não acha que dá pra usar esses dados pra saber se os dados de mobilidade tem correlação com o R0
https://twitter.com/JoaoCarabetta/status/1244044179430420489?s=20

**Comment by flaviovdf** [comment]
Não são bons -> vai dar ruim. Só fiz ajustar um SEIR já pronto para a curva do brasil, foi esse aqui: https://gabgoh.github.io/COVID/. Nem fiz fit de dados, fui na mão mesmo.

**Comment by flaviovdf** [comment]
Acho que dá sim, seria uma correlação bacana.
