### ISSUE TITLE
Versão das dependências utilizadas

### ISSUE THREAD

**Issue by jxonas** [flaviovdf/covid19#2]
Flavio, obrigado pela aula! Didática e códigos super claros, fáceis de compreender =)

Estou com dificuldade, no entanto, de executar o código localmente devido a inconsistências entre algumas dependências. Em particular, estou preso na célula 3 no que acho ser desencontro de versões entre `pandas` e `rpy2`:

```
...
AttributeError: module 'rpy2.robjects.pandas2ri' has no attribute 'ri2py'
```

Você consegue disponibilizar de alguma forma (por exemplo um `requirements.txt`) com os números de versão das bibliotecas utilizadas?

Obrigado!

**Comment by flaviovdf** [comment]
Você precisa instalar o rpy2. Depois disso, instale o pacote EpiEstimo no
*R*.

--
Flavio

**Comment by jxonas** [comment]
@flaviovdf obrigado pela resposta! Eu já tinha todas as dependências instaladas no entanto, inclusive R.

O problema estava na versão da biblioteca rpy2. A mais recente converte automaticamente o output do R para dataframe pandas, tornando mais simples a interface. Como configurei meu ambiente do zero, acabei baixando a versão mais recente de todas as bibliotecas...

Criei um fork do seu código pra ajustar de acordo com o meu ambiente. Finalizando esse processo documento a versão exata de cada biblioteca utilizada e posto aqui de volta, para referência futura.

Obrigado mais uma vez por compartilhar e explicar tão bem essas análises!
